// import type { Metadata } from "next";
// import localFont from "next/font/local";

import { Footer } from "../Footer";
import { Menu } from "../Menu";

/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

*/

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /*
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
  */
  return (
    <div className="container is-max-desktop">
      <Menu />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
